# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/player_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 618)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.playlistLbl = QtWidgets.QLabel(self.centralwidget)
        self.playlistLbl.setObjectName("playlistLbl")
        self.gridLayout.addWidget(self.playlistLbl, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.curMusictimeLbl = QtWidgets.QLabel(self.centralwidget)
        self.curMusictimeLbl.setMinimumSize(QtCore.QSize(40, 17))
        self.curMusictimeLbl.setMaximumSize(QtCore.QSize(40, 17))
        self.curMusictimeLbl.setObjectName("curMusictimeLbl")
        self.horizontalLayout.addWidget(self.curMusictimeLbl)
        self.musicProgress = QtWidgets.QSlider(self.centralwidget)
        self.musicProgress.setOrientation(QtCore.Qt.Horizontal)
        self.musicProgress.setObjectName("musicProgress")
        self.horizontalLayout.addWidget(self.musicProgress)
        self.totalMusictimeLbl = QtWidgets.QLabel(self.centralwidget)
        self.totalMusictimeLbl.setMinimumSize(QtCore.QSize(40, 17))
        self.totalMusictimeLbl.setMaximumSize(QtCore.QSize(40, 17))
        self.totalMusictimeLbl.setObjectName("totalMusictimeLbl")
        self.horizontalLayout.addWidget(self.totalMusictimeLbl)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imgLbl = QtWidgets.QLabel(self.centralwidget)
        self.imgLbl.setMinimumSize(QtCore.QSize(50, 50))
        self.imgLbl.setMaximumSize(QtCore.QSize(50, 50))
        self.imgLbl.setText("")
        self.imgLbl.setObjectName("imgLbl")
        self.horizontalLayout_2.addWidget(self.imgLbl)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.musNameLbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.musNameLbl.setFont(font)
        self.musNameLbl.setObjectName("musNameLbl")
        self.verticalLayout_2.addWidget(self.musNameLbl)
        self.artistLbl = QtWidgets.QLabel(self.centralwidget)
        self.artistLbl.setObjectName("artistLbl")
        self.verticalLayout_2.addWidget(self.artistLbl)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.volDial = QtWidgets.QDial(self.centralwidget)
        self.volDial.setMaximumSize(QtCore.QSize(50, 50))
        self.volDial.setMaximum(100)
        self.volDial.setObjectName("volDial")
        self.horizontalLayout_2.addWidget(self.volDial)
        self.prevBtn = QtWidgets.QPushButton(self.centralwidget)
        self.prevBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.prevBtn.setStyleSheet("")
        self.prevBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/res/rewind.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevBtn.setIcon(icon)
        self.prevBtn.setIconSize(QtCore.QSize(30, 30))
        self.prevBtn.setObjectName("prevBtn")
        self.horizontalLayout_2.addWidget(self.prevBtn)
        self.playBtn = QtWidgets.QPushButton(self.centralwidget)
        self.playBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.playBtn.setStyleSheet("")
        self.playBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/res/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/res/pause.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.playBtn.setIcon(icon1)
        self.playBtn.setIconSize(QtCore.QSize(30, 30))
        self.playBtn.setCheckable(True)
        self.playBtn.setChecked(False)
        self.playBtn.setAutoExclusive(False)
        self.playBtn.setAutoDefault(False)
        self.playBtn.setDefault(False)
        self.playBtn.setFlat(False)
        self.playBtn.setObjectName("playBtn")
        self.horizontalLayout_2.addWidget(self.playBtn)
        self.nextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.nextBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.nextBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.nextBtn.setStyleSheet("")
        self.nextBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/res/forward.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextBtn.setIcon(icon2)
        self.nextBtn.setIconSize(QtCore.QSize(30, 30))
        self.nextBtn.setObjectName("nextBtn")
        self.horizontalLayout_2.addWidget(self.nextBtn)
        self.rptBtn = QtWidgets.QPushButton(self.centralwidget)
        self.rptBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.rptBtn.setStyleSheet("")
        self.rptBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/res/repeat.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rptBtn.setIcon(icon3)
        self.rptBtn.setIconSize(QtCore.QSize(30, 30))
        self.rptBtn.setObjectName("rptBtn")
        self.horizontalLayout_2.addWidget(self.rptBtn)
        self.shfBtn = QtWidgets.QPushButton(self.centralwidget)
        self.shfBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.shfBtn.setStyleSheet("")
        self.shfBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/res/shuffle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shfBtn.setIcon(icon4)
        self.shfBtn.setIconSize(QtCore.QSize(30, 30))
        self.shfBtn.setObjectName("shfBtn")
        self.horizontalLayout_2.addWidget(self.shfBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuConnection = QtWidgets.QMenu(self.menuSetting)
        self.menuConnection.setObjectName("menuConnection")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actReconnect = QtWidgets.QAction(MainWindow)
        self.actReconnect.setObjectName("actReconnect")
        self.actEditConneect = QtWidgets.QAction(MainWindow)
        self.actEditConneect.setObjectName("actEditConneect")
        self.menuConnection.addAction(self.actReconnect)
        self.menuConnection.addAction(self.actEditConneect)
        self.menuSetting.addSeparator()
        self.menuSetting.addAction(self.menuConnection.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.playlistLbl.setText(_translate("MainWindow", "재생목록"))
        self.curMusictimeLbl.setText(_translate("MainWindow", "0:00"))
        self.totalMusictimeLbl.setText(_translate("MainWindow", "0:00"))
        self.musNameLbl.setText(_translate("MainWindow", "Music"))
        self.artistLbl.setText(_translate("MainWindow", "Artist"))
        self.menuSetting.setTitle(_translate("MainWindow", "설정"))
        self.menuConnection.setTitle(_translate("MainWindow", "연결..."))
        self.actReconnect.setText(_translate("MainWindow", "재연결"))
        self.actEditConneect.setText(_translate("MainWindow", "연결 편집"))


import ButtonImg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
